imports:
    - { resource: 'services/installer.yml' }

services:
    Youwe\Pimcore\WorkflowGui\Resolver\ConfigFileResolver:
        arguments:
            - '%workflow_gui.config%'

    Youwe\Pimcore\WorkflowGui\Repository\WorkflowRepository:
        arguments:
            - '@Youwe\Pimcore\WorkflowGui\Resolver\ConfigFileResolver'

    Youwe\Pimcore\WorkflowGui\Controller\WorkflowController:
        autowire: true
        autoconfigure: true
        arguments:
            - '@Youwe\Pimcore\WorkflowGui\Repository\WorkflowRepository'
            - '@Youwe\Pimcore\WorkflowGui\Resolver\ConfigFileResolver'
            - '@kernel'
            - '@Pimcore\Cache\Symfony\CacheClearer'
            - '@security.token_storage'
        tags:
            - { name: controller.service_arguments }
        calls:
            - { method: setContainer, arguments: [ '@service_container' ] }
